uncategorized:
  discoursecord_enabled:
    default: true
    client: true
    description: "Enable the Discoursecord plugin with advanced admin interface featuring up/down arrows and color pickers"

  discoursecord_group_rankings:
    default: ""
    client: true
    description: "Use the enhanced admin interface at /admin/plugins/discoursecord/settings for up/down arrows, drag-and-drop reordering, and visual controls"

  discoursecord_group_colors:
    default: ""
    client: true
    description: "Use the enhanced admin interface at /admin/plugins/discoursecord/settings for interactive color pickers and visual color management"
