uncategorized:
  discoursecord_enabled:
    default: true
    client: true
    description: "Enable the Discoursecord plugin with enhanced admin interface"

  discoursecord_group_rankings:
    default: ""
    client: true
    description: "Group rankings - Use the enhanced admin interface below"

  discoursecord_group_colors:
    default: '{"admin":"#e74c3c","staff":"#f39c12","moderator":"#3498db","trust_level_4":"#8e44ad","trust_level_3":"#27ae60","trust_level_2":"#16a085","trust_level_1":"#7f8c8d"}'
    client: true
    description: "Group colors - Use the enhanced admin interface below"
