plugins:
  discoursecord_enabled:
    default: true
    client: true

  discoursecord_group_rankings:
    type: list
    default: "admin|staff|moderator|trust_level_4|trust_level_3|trust_level_2|trust_level_1"
    list_type: compact
    client: true

  discoursecord_group_colors:
    default: '{"admin":"#e74c3c","staff":"#f39c12","moderator":"#3498db","trust_level_4":"#8e44ad","trust_level_3":"#27ae60","trust_level_2":"#16a085","trust_level_1":"#7f8c8d"}'
    client: true
