discoursecord:
  discoursecord_enabled:
    type: bool
    default: true

  discoursecord_group_rankings:
    type: list
    default: admin,staff,moderator,trust_level_4,trust_level_3,trust_level_2,trust_level_1

  discoursecord_group_colors:
    type: json
    default: '{"admin":"#e74c3c","staff":"#f39c12","moderator":"#3498db","trust_level_4":"#8e44ad","trust_level_3":"#27ae60","trust_level_2":"#16a085","trust_level_1":"#7f8c8d"}'
